# This rule is not used by the project hotswap-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over hotswap.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hotswap-operator
    app.kubernetes.io/managed-by: kustomize
  name: hotswappolicy-admin-role
rules:
- apiGroups:
  - hotswap.io
  resources:
  - hotswappolicies
  verbs:
  - '*'
- apiGroups:
  - hotswap.io
  resources:
  - hotswappolicies/status
  verbs:
  - get
